name: pixelwise
channels:
  - defaults
dependencies:
  - python=3.7
  - pyyaml
  - numpy
  - jupyter
  - scikit-image
  - tensorboard
  - seaborn
  - pillow[version='<7']
  - cudatoolkit=10.1
  - pytorch
  - torchvision

